# Generated by Django 4.1.5 on 2023-03-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userpic',
            field=models.ImageField(default='default_userpic.png', upload_to='images/profile/'),
        ),
    ]
