# Generated by Django 4.1.5 on 2023-03-14 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_profile_userpic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='userpic',
            new_name='avatar',
        ),
    ]
