# Generated by Django 4.1.5 on 2023-03-25 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_userssubscribed_category_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='subscribers',
            new_name='user',
        ),
    ]
